/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright (c) 2026 Tomonori Kouya. Based on GQD (Mian Lu) and QD (Bailey et al., LBNL).
 *
 * Float-precision common header.  Mirrors common.cuh for the
 * gds_real / gts_real / gqs_real layers.  All identifiers live in the
 * same global namespace as the double versions because the underlying
 * scalar type differs (float vs. double), so there is no symbol clash.
 */
#ifndef __GQS_COMMON_CUH__
#define __GQS_COMMON_CUH__

#include <stdio.h>
#include <stdlib.h>
#include <cmath>
#include "gqd_type.h"
#include "cuda_header.cu"

/* type construction (float overloads) */
extern __device__ __host__
gds_real make_ds( const float x, const float y );

extern __device__ __host__
gds_real make_ds( const float x );

extern __device__ __host__
gts_real make_ts( const float x, const float y, const float z );

extern __device__ __host__
gts_real make_ts( const float x );

extern __device__ __host__
gqs_real make_qs( const float x,
                  const float y,
                  const float z,
                  const float w );

extern __device__ __host__
gqs_real make_qs( const float x );

/*======== float constants ========
 * Each value is the float-precision representation of the well-known
 * mathematical constant.  The "_x" component of a multi-float is the
 * leading float; the "_y" / "_z" / "_w" components carry the residual
 * down to the precision of the float type (24 bits).  Values were
 * generated by truncating the double-precision constants from
 * common.cuh, then computing the float residual in double arithmetic
 * and storing it as the next limb (cf. ds_from_dd in dtq-0.0.2).
 */

/* All multi-float constants below are derived from the QD reference
 * values in common.cuh by staircase float decomposition: each limb
 * stores the rounding residual of the previous limb, so all 2/3/4
 * floats together carry the full ~48 / ~72 / ~96 bits of precision. */

/* DS (single-double, 2 floats) */
#define _ds_eps   (1.4210854715202004e-14f)            /* 2^-46 */
#define _ds_e     make_ds(2.71828175e+00f,  8.25484037e-08f)
#define _ds_log2  make_ds(6.93147182e-01f, -1.90465421e-09f)
#define _ds_2pi   make_ds(6.28318548e+00f, -1.74845553e-07f)
#define _ds_pi    make_ds(3.14159274e+00f, -8.74227766e-08f)
#define _ds_pi2   make_ds(1.57079637e+00f, -4.37113883e-08f)
#define _ds_pi4   make_ds(7.85398185e-01f, -2.18556941e-08f)
#define _ds_pi16  make_ds(1.96349546e-01f, -5.46392354e-09f)
#define _ds_3pi4  make_ds(2.35619450e+00f, -5.96244032e-09f)

/* TS (triple-single, 3 floats) */
#define _ts_eps   (8.4703294725430034e-22f)            /* ~ 2^-70  (3*24-2 bits) */
#define _ts_e     make_ts(2.71828175e+00f,  8.25484037e-08f, -2.96405987e-15f)
#define _ts_log2  make_ts(6.93147182e-01f, -1.90465421e-09f, -8.78318374e-17f)
#define _ts_2pi   make_ts(6.28318548e+00f, -1.74845553e-07f, -6.86049804e-15f)
#define _ts_pi    make_ts(3.14159274e+00f, -8.74227766e-08f, -3.43024902e-15f)
#define _ts_pi2   make_ts(1.57079637e+00f, -4.37113883e-08f, -1.71512451e-15f)
#define _ts_pi4   make_ts(7.85398185e-01f, -2.18556941e-08f, -8.57562255e-16f)
#define _ts_pi1024 make_ts(3.06796166e-03f, -8.53738052e-11f, -3.34985256e-18f)

/* QS (quadruple-single, 4 floats) */
#define _qs_eps   (5.0487894595025505e-29f)            /* ~ 2^-93  (4*24-3 bits) */
#define _qs_e     make_qs(2.71828175e+00f,  8.25484037e-08f, -2.96405987e-15f,  9.26442286e-23f)
#define _qs_log2  make_qs(6.93147182e-01f, -1.90465421e-09f, -8.78318374e-17f,  2.89513214e-24f)
#define _qs_2pi   make_qs(6.28318548e+00f, -1.74845553e-07f, -6.86049804e-15f,  5.29395592e-23f)
#define _qs_pi    make_qs(3.14159274e+00f, -8.74227766e-08f, -3.43024902e-15f,  2.64697796e-23f)
#define _qs_pi2   make_qs(1.57079637e+00f, -4.37113883e-08f, -1.71512451e-15f,  1.32348898e-23f)
#define _qs_pi4   make_qs(7.85398185e-01f, -2.18556941e-08f, -8.57562255e-16f,  6.61744490e-24f)
#define _qs_pi1024 make_qs(3.06796166e-03f, -8.53738052e-11f, -3.34985256e-18f, 2.58493941e-26f)
#define _qs_3pi4  make_qs(2.35619450e+00f, -5.96244032e-09f,  9.18485073e-17f,  2.48154184e-24f)

/*======== constant-memory tables ========
 *
 * Two declaration modes, mirroring common.cuh:
 *   (A) WITHOUT -rdc=true  : `static __device__ __constant__` — per-TU
 *       private storage, living in the single TU that includes
 *       common_s.cu via gqs.cu (original gdtq stand-alone behaviour).
 *   (B) WITH -rdc=true (e.g. bncmatmul's libbncmm_cuda.a) : `extern
 *       __device__ __constant__` here, with the actual storage defined
 *       once in common_s.cu.  Per-TU static storage would otherwise
 *       cause "nvlink fatal : Internal error: .nv.constant3 section
 *       size mismatch" at device-link time.
 * __CUDACC_RDC__ is auto-defined by nvcc when -rdc=true is passed.
 */
#define n_ds_inv_fact (15)
#define n_ts_inv_fact (15)

#ifdef __CUDACC_RDC__
extern __device__ __constant__ gds_real ds_inv_fact[n_ds_inv_fact];
extern __device__ __constant__ gds_real d_ds_sin_table[4];
extern __device__ __constant__ gds_real d_ds_cos_table[4];

extern __device__ __constant__ gts_real ts_inv_fact[n_ts_inv_fact];
extern __device__ __constant__ gts_real d_ts_sin_table[256];
extern __device__ __constant__ gts_real d_ts_cos_table[256];

extern __device__ __constant__ gqs_real qs_inv_fact[15];
extern __device__ __constant__ gqs_real d_qs_sin_table[256];
extern __device__ __constant__ gqs_real d_qs_cos_table[256];
#else
static __device__ __constant__ gds_real ds_inv_fact[n_ds_inv_fact];
static __device__ __constant__ gds_real d_ds_sin_table[4];
static __device__ __constant__ gds_real d_ds_cos_table[4];

static __device__ __constant__ gts_real ts_inv_fact[n_ts_inv_fact];
static __device__ __constant__ gts_real d_ts_sin_table[256];
static __device__ __constant__ gts_real d_ts_cos_table[256];

static __device__ __constant__ gqs_real qs_inv_fact[15];
static __device__ __constant__ gqs_real d_qs_sin_table[256];
static __device__ __constant__ gqs_real d_qs_cos_table[256];
#endif

static const int n_qs_inv_fact = 15;

/* initialization */
extern void GDSStart(const int device);
extern void GDSEnd();
extern void GTSStart(const int device);
extern void GTSEnd();
extern void GQSStart(const int device);
extern void GQSEnd();

#endif /* __GQS_COMMON_CUH__ */
